= Openprice RESTful API Getting Started Guide
Yuan Ji;
:doctype: book
:toc: left
:toclevels: 4
:source-highlighter: highlightjs

[introduction]
= Introduction

Openprice API is a RESTful web service for managing user data and user's receipt data.
It uses hypermedia to describe the relationships between resources and to allow navigation between them.

[getting-started]
= Getting started



[getting-started-running-the-service]
== Running the service
Openprice RESTful API is written using http://projects.spring.io/spring-boot[Spring Boot] which
makes it easy to get it up and running so that you can start exploring the REST API.

We have DEV environment for front-end developer to use for their Web and mobile app development.
The entry point is at `https://dev-api.theopenprice.com/api`.

You can check that the service is up and running by executing a simple request using
cURL:

`curl https://dev-api.theopenprice.com/api`

This request should yield the following response:

```
{
   "authenticated":false,
   "currentUser":null,
   "_links":{
      "self":{
         "href":"https://dev-api.theopenprice.com/api"
      },
      "signin":{
         "href":"https://dev-api.theopenprice.com/api/signin"
      },
      "registration":{
         "href":"https://dev-api.theopenprice.com/api/public/registration"
      },
      "forgetPassword":{
         "href":"https://dev-api.theopenprice.com/api/public/resetPasswordRequests"
      },
      "resetPassword":{
         "href":"https://dev-api.theopenprice.com/api/public/resetPasswordRequests/{requestId}",
         "templated":true
      }
   }
}
```

Note the `_links` in the JSON response. They are key to navigating the API.

[api-docs]
= RESTful API Documentations

link:api-guide.html[Public API Documentation]

link:user-api-guide.html[User API Documentation]

link:admin-api-guide.html[Admin API Documentation]
