= Openprice RESTful API Getting Started Guide
Yuan Ji;
:doctype: book
:toc: left
:toclevels: 4
:source-highlighter: highlightjs

[introduction]
= Introduction

Openprice API is a RESTful web service for managing user data and user's receipt data.
It uses hypermedia to describe the relationships between resources and to allow navigation between them.

[getting-started]
= Getting started



[getting-started-running-the-service]
== Running the service
Openprice RESTful API is written using http://projects.spring.io/spring-boot[Spring Boot] which
makes it easy to get it up and running so that you can start exploring the REST API.

We have DEV environment for front-end developer to use for their Web and mobile app development.
The entry point is at `http://104.154.88.206:7800/api`.

You can check that the service is up and running by executing a simple request using
cURL:

`curl http://104.154.88.206:7800/api`

This request should yield the following response:

`{"authenticated":false,"currentUser":null,"_links":{"self":{"href":"http://104.154.88.206:7800/api"},"signin":{"href":"http://104.154.88.206:7800/api/signin"},"registration":{"href":"http://104.154.88.206:7800/api/public/registration"},"forgetPassword":{"href":"http://104.154.88.206:7800/api/public/resetPasswordRequests"},"resetPassword":{"href":"http://104.154.88.206:7800/api/public/resetPasswordRequests/{requestId}","templated":true}}}`

Note the `_links` in the JSON response. They are key to navigating the API.

[api-docs]
= RESTful API Documentations

link:api-guide.html[Public API Documentation]

link:user-api-guide.html[User API Documentation]

link:admin-api-guide.html[Admin API Documentation]
