server:
    port: 7901

spring:
    datasource:
        url: jdbc:mysql://mysql:3306/openprice
        username: openprice
        password: openprice
        driver-class-name: com.mysql.jdbc.Driver
        test-on-borrow: true
        validation-query: SELECT 1
    jpa:
        database: MYSQL
        show-sql: false
        hibernate:
            ddl-auto: validate

application:
    settings:
        file:
            virtual: false
            imageRootFolder: /groundtruth/images
    