spring:
    datasource:
        url: jdbc:mysql://mysql:3306/openprice
        username: openprice
        password: openprice
        driver-class-name: com.mysql.jdbc.Driver
        test-on-borrow: true
        validation-query: SELECT 1
    jpa:
        database: MYSQL
        show-sql: false
        hibernate:
            ddl-auto: validate

application:
    settings:
        email:
            systemName: GroundTruth Inc.
            systemEmail: no-reply@theopenprice.com
            adminName: Open Price
            adminEmail: admin@theopenprice.com
            webServerUrl: http://104.154.88.206:8080
        file:
            virtual: false
            imageRootFolder: /groundtruth/images
        process:
            cloudEngineEnabled: true
            numberOfServers: 1
            waitSeconds: 0
            cloudApplicationId: openprice
            cloudPassword: VGe2YmGwhmKrd6YDxR3tEul2
