server:
    port: 7900

application:
    email:
        systemName: GroundTruth Inc.
        systemEmail: no-reply@openprice.com
        adminName: Open Price
        adminEmail: admin@openprice.com

spring:
    datasource:
        test-on-borrow: true
        validation-query: SELECT 1
    jpa:
        database: MYSQL
        show-sql: false
        hibernate:
            ddl-auto: validate

---

spring:
    profiles: docker

    datasource:
        url: jdbc:mysql://mysql:3306/openprice
        username: openprice
        password: openprice
        driver-class-name: com.mysql.jdbc.Driver

application:
    email:
      webServerUrl: http://104.154.88.206:8080
    file:
        virtual: false
        imageRootFolder: /groundtruth/images

---

spring:
    profiles: ocr
    
application:
    process:
        serverPrefix: openprice-server-ocr-
        numberOfServers: 1
        serverPort: 7901
