server:
    port: 7900

spring:
    datasource:
        url: jdbc:mysql://mysql:3306/openprice
        username: openprice
        password: openprice
        driver-class-name: com.mysql.jdbc.Driver
        test-on-borrow: true
        validation-query: SELECT 1
    jpa:
        database: MYSQL
        show-sql: false
        hibernate:
            ddl-auto: validate

application:
    email:
        systemName: GroundTruth Inc.
        systemEmail: no-reply@openprice.com
        adminName: Open Price
        adminEmail: admin@openprice.com
        webServerUrl: http://104.154.88.206:8080
    settings:
        file:
            virtual: false
            imageRootFolder: /groundtruth/images
        process:
            serverPrefix: openprice-server-ocr-
            numberOfServers: 2
            serverPort: 7901
