server:
    port: 7801

application:
    token:
        secret: skdjvjvndjwkenfnhvjksknsjndjsdnf
    email:
        systemName: GroundTruth Inc.
        systemEmail: no-reply@openprice.com
        adminName: Open Price
        adminEmail: admin@openprice.com

spring:
    datasource:
        test-on-borrow: true
        validation-query: SELECT 1
    jpa:
        database: MYSQL
        show-sql: false
        hibernate:
            ddl-auto: validate

---

spring:
    profiles: local

    datasource:
        url: jdbc:mysql://localhost:3306/openpricelocal
        username: openprice
        password: openprice
        driver-class-name: com.mysql.jdbc.Driver

application:
    file:
        virtual: false
        imageRootFolder: /tmp/groundtruth/images

---

spring:
    profiles: docker

    datasource:
        url: jdbc:mysql://mysql:3306/openprice
        username: openprice
        password: openprice
        driver-class-name: com.mysql.jdbc.Driver

application:
    file:
        virtual: false
        imageRootFolder: /groundtruth/images
