#!/bin/bash

cd ~/openprice-backend
git pull

cd ~/openprice-backend
mvn clean install -Pdev

cd ~/openprice-backend/server-web-api
mvn docker:build

cd ~/openprice-backend/server-ocr
mvn docker:build

cd ~/openprice-backend/server-docs
mvn docker:build

docker run --name openprice-mysql -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=openprice -e MYSQL_USER=openprice -e MYSQL_PASSWORD=openprice -p 3306:3306 -d mysql:5.6
docker run --name openprice-server-ocr-1 -d -e SPRING_PROFILES_ACTIVE=dev,docker,noemail -e LOGGING_FILE_FOLDER=/groundtruth/logs -e OCR_SERVER_NAME=ocr1 -v ~/groundtruth/logs:/groundtruth/logs -v ~/groundtruth/images:/groundtruth/images openprice/openprice-server-ocr
docker run --name openprice-server-ocr-2 -d -e SPRING_PROFILES_ACTIVE=dev,docker,noemail -e LOGGING_FILE_FOLDER=/groundtruth/logs -e OCR_SERVER_NAME=ocr2 -v ~/groundtruth/logs:/groundtruth/logs -v ~/groundtruth/images:/groundtruth/images openprice/openprice-server-ocr
docker run --name openprice-server-web-api -d -p 7800:7800 -e SPRING_PROFILES_ACTIVE=dev,docker,noemail -e LOGGING_FILE_FOLDER=/groundtruth/logs -v ~/groundtruth/logs:/groundtruth/logs -v ~/groundtruth/images:/groundtruth/images --link openprice-mysql:mysql --link openprice-server-ocr-1:openprice-server-ocr-1 --link openprice-server-ocr-2:openprice-server-ocr-2 openprice/openprice-server-web-api
docker run --name openprice-server-docs -p 8080:8080 -d openprice/openprice-server-docs
