spring:
    datasource:
        url: jdbc:mysql://mysql:3306/openprice
        username: openprice
        password: openprice
        driver-class-name: com.mysql.jdbc.Driver
        test-on-borrow: true
        validation-query: SELECT 1
    jpa:
        database: MYSQL
        show-sql: false
        hibernate:
            ddl-auto: validate

multipart:
    maxFileSize: 10Mb
    
application:
    settings:
        email:
            systemName: GroundTruth Inc.
            systemEmail: no-reply@openprice.com
            adminName: Open Price
            adminEmail: admin@openprice.com
            webServerUrl: http://104.197.105.245:8080
        internal:
            serverHost: openprice-server-internal-api
            serverPort: 8080
        file:
            virtual: false
            imageRootFolder: /groundtruth/images

