#!/bin/bash

docker stop openprice-server-web-api
docker rm openprice-server-web-api

docker stop openprice-server-ocr-1
docker rm openprice-server-ocr-1

docker stop openprice-server-ocr-2
docker rm openprice-server-ocr-2
